// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package sqlc

import (
	"context"
	"time"
)

const addMeditation = `-- name: AddMeditation :exec
INSERT INTO meditations DEFAULT VALUES
`

func (q *Queries) AddMeditation(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, addMeditation)
	return err
}

const addSport = `-- name: AddSport :exec
INSERT INTO sports (name) VALUES ($1)
`

func (q *Queries) AddSport(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addSport, name)
	return err
}

const getMeditationToday = `-- name: GetMeditationToday :one
SELECT 1 FROM meditations WHERE created_at >= $1 AND created_at < $2 LIMIT 1
`

type GetMeditationTodayParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) GetMeditationToday(ctx context.Context, arg GetMeditationTodayParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMeditationToday, arg.CreatedAt, arg.CreatedAt_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
