// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT id, password_hash FROM users WHERE username = $1
`

type GetLoginUserRow struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) GetLoginUser(ctx context.Context, username string) (GetLoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginUser, username)
	var i GetLoginUserRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.username
FROM user_sessions
JOIN users ON users.id = user_sessions.user_id
WHERE user_sessions.token_hash = $1 AND user_sessions.expires_at > NOW()
`

type GetSessionUserRow struct {
	ID       int64
	Username string
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
