// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO financial_horizon_budgets (user_id, name, allocated_amount)
VALUES ($1, $2, $3) RETURNING id, name, allocated_amount
`

type CreateBudgetParams struct {
	UserID          int64
	Name            string
	AllocatedAmount float64
}

type CreateBudgetRow struct {
	ID              int64
	Name            string
	AllocatedAmount float64
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (CreateBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, createBudget, arg.UserID, arg.Name, arg.AllocatedAmount)
	var i CreateBudgetRow
	err := row.Scan(&i.ID, &i.Name, &i.AllocatedAmount)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM financial_horizon_budgets WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBudget, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBudgetUsedAmount = `-- name: GetBudgetUsedAmount :one
SELECT COALESCE(SUM(amount), 0)::double precision FROM financial_horizon_deductions
WHERE budget_id = $1 AND user_id = $2 AND is_active = true
`

type GetBudgetUsedAmountParams struct {
	BudgetID sql.NullInt64
	UserID   int64
}

func (q *Queries) GetBudgetUsedAmount(ctx context.Context, arg GetBudgetUsedAmountParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getBudgetUsedAmount, arg.BudgetID, arg.UserID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, name, allocated_amount FROM financial_horizon_budgets
WHERE user_id = $1 ORDER BY created_at ASC, id ASC
`

type ListBudgetsRow struct {
	ID              int64
	Name            string
	AllocatedAmount float64
}

func (q *Queries) ListBudgets(ctx context.Context, userID int64) ([]ListBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsRow
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AllocatedAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE financial_horizon_budgets
SET name = $1, allocated_amount = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND user_id = $4
RETURNING id, name, allocated_amount
`

type UpdateBudgetParams struct {
	Name            string
	AllocatedAmount float64
	ID              int64
	UserID          int64
}

type UpdateBudgetRow struct {
	ID              int64
	Name            string
	AllocatedAmount float64
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (UpdateBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, updateBudget,
		arg.Name,
		arg.AllocatedAmount,
		arg.ID,
		arg.UserID,
	)
	var i UpdateBudgetRow
	err := row.Scan(&i.ID, &i.Name, &i.AllocatedAmount)
	return i, err
}
