// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countDefaultCategories = `-- name: CountDefaultCategories :one
SELECT COUNT(*) FROM financial_horizon_categories WHERE is_default = true
`

func (q *Queries) CountDefaultCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDefaultCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO financial_horizon_categories (user_id, name, icon, color, is_default)
VALUES ($1, $2, $3, $4, false)
RETURNING id, name, icon, color, is_default, user_id
`

type CreateCategoryParams struct {
	UserID sql.NullInt64
	Name   string
	Icon   string
	Color  string
}

type CreateCategoryRow struct {
	ID        int64
	Name      string
	Icon      string
	Color     string
	IsDefault bool
	UserID    sql.NullInt64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.IsDefault,
		&i.UserID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, icon, color, is_default, user_id
FROM financial_horizon_categories
WHERE user_id IS NULL OR user_id = $1
ORDER BY is_default DESC, name ASC
`

type ListCategoriesRow struct {
	ID        int64
	Name      string
	Icon      string
	Color     string
	IsDefault bool
	UserID    sql.NullInt64
}

func (q *Queries) ListCategories(ctx context.Context, userID sql.NullInt64) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.IsDefault,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultCategory = `-- name: SeedDefaultCategory :exec
INSERT INTO financial_horizon_categories (name, icon, color, is_default)
VALUES ($1, $2, $3, true) ON CONFLICT DO NOTHING
`

type SeedDefaultCategoryParams struct {
	Name  string
	Icon  string
	Color string
}

func (q *Queries) SeedDefaultCategory(ctx context.Context, arg SeedDefaultCategoryParams) error {
	_, err := q.db.ExecContext(ctx, seedDefaultCategory, arg.Name, arg.Icon, arg.Color)
	return err
}
