// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gym.sql

package sqlc

import (
	"context"
	"time"
)

const createGymExerciseSet = `-- name: CreateGymExerciseSet :one
INSERT INTO gym_exercise_sets (gym_visit_exercise_id, set_number, reps, weight)
VALUES ($1, $2, $3, $4) RETURNING id, set_number, reps, weight
`

type CreateGymExerciseSetParams struct {
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             *float64
}

type CreateGymExerciseSetRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) CreateGymExerciseSet(ctx context.Context, arg CreateGymExerciseSetParams) (CreateGymExerciseSetRow, error) {
	row := q.db.QueryRowContext(ctx, createGymExerciseSet,
		arg.GymVisitExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
	)
	var i CreateGymExerciseSetRow
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
	)
	return i, err
}

const createGymReminderNotification = `-- name: CreateGymReminderNotification :one
INSERT INTO notifications (user_id, source, title, body, target_path, priority, metadata)
SELECT $1, $2, 'Time for the gym', 'Your 3:30 PM gym reminder. Mark your visit when you are done.', '/gym-visits', 1, jsonb_build_object('reminder_date', $3::text)
WHERE NOT EXISTS (
    SELECT 1 FROM gym_reminder_deliveries WHERE user_id = $1 AND reminder_date = ($3::text)::date
)
RETURNING id
`

type CreateGymReminderNotificationParams struct {
	UserID  int64
	Source  string
	Column3 string
}

func (q *Queries) CreateGymReminderNotification(ctx context.Context, arg CreateGymReminderNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGymReminderNotification, arg.UserID, arg.Source, arg.Column3)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGymVisit = `-- name: CreateGymVisit :one
INSERT INTO gym_visits DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateGymVisit(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGymVisit)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGymVisitExercise = `-- name: CreateGymVisitExercise :one
INSERT INTO gym_visit_exercises (gym_visit_id, name) VALUES ($1, $2) RETURNING id, name
`

type CreateGymVisitExerciseParams struct {
	GymVisitID int64
	Name       string
}

type CreateGymVisitExerciseRow struct {
	ID   int64
	Name string
}

func (q *Queries) CreateGymVisitExercise(ctx context.Context, arg CreateGymVisitExerciseParams) (CreateGymVisitExerciseRow, error) {
	row := q.db.QueryRowContext(ctx, createGymVisitExercise, arg.GymVisitID, arg.Name)
	var i CreateGymVisitExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGymVisit = `-- name: DeleteGymVisit :execrows
DELETE FROM gym_visits WHERE id = $1
`

func (q *Queries) DeleteGymVisit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGymVisit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dismissGymReminder = `-- name: DismissGymReminder :exec
UPDATE notifications SET dismissed_at = NOW() WHERE id = $1
`

func (q *Queries) DismissGymReminder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, dismissGymReminder, id)
	return err
}

const getGymVisitToday = `-- name: GetGymVisitToday :one
SELECT id FROM gym_visits WHERE created_at >= $1 AND created_at < $2
ORDER BY created_at DESC LIMIT 1
`

type GetGymVisitTodayParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) GetGymVisitToday(ctx context.Context, arg GetGymVisitTodayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGymVisitToday, arg.CreatedAt, arg.CreatedAt_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const gymReminderExists = `-- name: GymReminderExists :one
SELECT EXISTS(SELECT 1 FROM notifications
WHERE id = $1 AND user_id = $2 AND source = $3 AND dismissed_at IS NULL)
`

type GymReminderExistsParams struct {
	ID     int64
	UserID int64
	Source string
}

func (q *Queries) GymReminderExists(ctx context.Context, arg GymReminderExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, gymReminderExists, arg.ID, arg.UserID, arg.Source)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const gymVisitExists = `-- name: GymVisitExists :one
SELECT 1 FROM gym_visits WHERE id = $1
`

func (q *Queries) GymVisitExists(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, gymVisitExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listGymExerciseSets = `-- name: ListGymExerciseSets :many
SELECT id, set_number, reps, weight FROM gym_exercise_sets
WHERE gym_visit_exercise_id = $1 ORDER BY set_number ASC
`

type ListGymExerciseSetsRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) ListGymExerciseSets(ctx context.Context, gymVisitExerciseID int64) ([]ListGymExerciseSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGymExerciseSets, gymVisitExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGymExerciseSetsRow
	for rows.Next() {
		var i ListGymExerciseSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGymReminderUsers = `-- name: ListGymReminderUsers :many
SELECT id FROM users
`

func (q *Queries) ListGymReminderUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGymReminderUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGymVisitExercises = `-- name: ListGymVisitExercises :many
SELECT id, name FROM gym_visit_exercises WHERE gym_visit_id = $1 ORDER BY id ASC
`

type ListGymVisitExercisesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListGymVisitExercises(ctx context.Context, gymVisitID int64) ([]ListGymVisitExercisesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGymVisitExercises, gymVisitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGymVisitExercisesRow
	for rows.Next() {
		var i ListGymVisitExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGymVisits = `-- name: ListGymVisits :many
SELECT id, created_at FROM gym_visits ORDER BY created_at DESC, id DESC
`

type ListGymVisitsRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) ListGymVisits(ctx context.Context) ([]ListGymVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGymVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGymVisitsRow
	for rows.Next() {
		var i ListGymVisitsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordGymReminderDelivery = `-- name: RecordGymReminderDelivery :exec
INSERT INTO gym_reminder_deliveries (user_id, reminder_date, notification_id)
VALUES ($1, ($2::text)::date, $3)
`

type RecordGymReminderDeliveryParams struct {
	UserID         int64
	Column2        string
	NotificationID int64
}

func (q *Queries) RecordGymReminderDelivery(ctx context.Context, arg RecordGymReminderDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordGymReminderDelivery, arg.UserID, arg.Column2, arg.NotificationID)
	return err
}
