// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const dismissAllNotifications = `-- name: DismissAllNotifications :exec
UPDATE notifications SET dismissed_at = NOW()
WHERE user_id = $1 AND dismissed_at IS NULL
`

func (q *Queries) DismissAllNotifications(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, dismissAllNotifications, userID)
	return err
}

const dismissNotification = `-- name: DismissNotification :execrows
UPDATE notifications SET dismissed_at = NOW()
WHERE id = $1 AND user_id = $2 AND dismissed_at IS NULL
`

type DismissNotificationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DismissNotification(ctx context.Context, arg DismissNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissNotification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveNotifications = `-- name: ListActiveNotifications :many
SELECT id, source, title, body, target_path, priority, created_at
FROM notifications
WHERE user_id = $1 AND dismissed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListActiveNotificationsParams struct {
	UserID int64
	Limit  int32
}

type ListActiveNotificationsRow struct {
	ID         int64
	Source     string
	Title      string
	Body       sql.NullString
	TargetPath sql.NullString
	Priority   int16
	CreatedAt  time.Time
}

func (q *Queries) ListActiveNotifications(ctx context.Context, arg ListActiveNotificationsParams) ([]ListActiveNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNotificationsRow
	for rows.Next() {
		var i ListActiveNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.TargetPath,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
