// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"
)

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getProfileName = `-- name: GetProfileName :one
SELECT display_name FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetProfileName(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getProfileName, userID)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const saveProfile = `-- name: SaveProfile :exec
INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = NOW()
`

type SaveProfileParams struct {
	UserID      int64
	DisplayName string
}

func (q *Queries) SaveProfile(ctx context.Context, arg SaveProfileParams) error {
	_, err := q.db.ExecContext(ctx, saveProfile, arg.UserID, arg.DisplayName)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $1, updated_at = NOW() WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
