// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearNextMonthPurchases = `-- name: ClearNextMonthPurchases :exec
DELETE FROM next_month_purchases WHERE user_id = $1 AND target_month = ($2::text)::date
`

type ClearNextMonthPurchasesParams struct {
	UserID  int64
	Column2 string
}

func (q *Queries) ClearNextMonthPurchases(ctx context.Context, arg ClearNextMonthPurchasesParams) error {
	_, err := q.db.ExecContext(ctx, clearNextMonthPurchases, arg.UserID, arg.Column2)
	return err
}

const createNextMonthPurchase = `-- name: CreateNextMonthPurchase :one
INSERT INTO next_month_purchases (user_id, target_month, name, price, url)
VALUES ($1, ($2::text)::date, $3, $4, $5)
RETURNING id, name, price, url
`

type CreateNextMonthPurchaseParams struct {
	UserID  int64
	Column2 string
	Name    string
	Price   float64
	Url     sql.NullString
}

type CreateNextMonthPurchaseRow struct {
	ID    int64
	Name  string
	Price float64
	Url   sql.NullString
}

func (q *Queries) CreateNextMonthPurchase(ctx context.Context, arg CreateNextMonthPurchaseParams) (CreateNextMonthPurchaseRow, error) {
	row := q.db.QueryRowContext(ctx, createNextMonthPurchase,
		arg.UserID,
		arg.Column2,
		arg.Name,
		arg.Price,
		arg.Url,
	)
	var i CreateNextMonthPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Url,
	)
	return i, err
}

const deleteNextMonthPurchase = `-- name: DeleteNextMonthPurchase :execrows
DELETE FROM next_month_purchases
WHERE id = $1 AND user_id = $2 AND target_month = ($3::text)::date
`

type DeleteNextMonthPurchaseParams struct {
	ID      int64
	UserID  int64
	Column3 string
}

func (q *Queries) DeleteNextMonthPurchase(ctx context.Context, arg DeleteNextMonthPurchaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNextMonthPurchase, arg.ID, arg.UserID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNextMonthPurchases = `-- name: ListNextMonthPurchases :many
SELECT id, name, price, url FROM next_month_purchases
WHERE user_id = $1 AND target_month = ($2::text)::date
ORDER BY created_at DESC, id DESC
`

type ListNextMonthPurchasesParams struct {
	UserID  int64
	Column2 string
}

type ListNextMonthPurchasesRow struct {
	ID    int64
	Name  string
	Price float64
	Url   sql.NullString
}

func (q *Queries) ListNextMonthPurchases(ctx context.Context, arg ListNextMonthPurchasesParams) ([]ListNextMonthPurchasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNextMonthPurchases, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNextMonthPurchasesRow
	for rows.Next() {
		var i ListNextMonthPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
