// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO financial_horizon_subscriptions (user_id, name, amount, billing_cycle, billing_day, renewal_date, status, category_id, budget_id, deduction_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, amount, billing_cycle, billing_day, renewal_date, status, category_id, budget_id, deduction_id, notes, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID       int64
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        sql.NullString
}

type CreateSubscriptionRow struct {
	ID           int64
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.BillingCycle,
		arg.BillingDay,
		arg.RenewalDate,
		arg.Status,
		arg.CategoryID,
		arg.BudgetID,
		arg.DeductionID,
		arg.Notes,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.BillingCycle,
		&i.BillingDay,
		&i.RenewalDate,
		&i.Status,
		&i.CategoryID,
		&i.BudgetID,
		&i.DeductionID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM financial_horizon_subscriptions WHERE id = $1 AND user_id = $2
`

type DeleteSubscriptionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubscription, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBudgetName = `-- name: GetBudgetName :one
SELECT name FROM financial_horizon_budgets WHERE id = $1 AND user_id = $2
`

type GetBudgetNameParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetBudgetName(ctx context.Context, arg GetBudgetNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getBudgetName, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getCategoryName = `-- name: GetCategoryName :one
SELECT name FROM financial_horizon_categories WHERE id = $1
`

func (q *Queries) GetCategoryName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCategoryName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getSubscriptionTransactionStats = `-- name: GetSubscriptionTransactionStats :one
SELECT COALESCE(COUNT(id), 0)::bigint AS linked_count, COALESCE(SUM(amount), 0)::double precision AS total_spent
FROM financial_horizon_transactions WHERE subscription_id = $1 AND user_id = $2
`

type GetSubscriptionTransactionStatsParams struct {
	SubscriptionID sql.NullInt64
	UserID         int64
}

type GetSubscriptionTransactionStatsRow struct {
	LinkedCount int64
	TotalSpent  float64
}

func (q *Queries) GetSubscriptionTransactionStats(ctx context.Context, arg GetSubscriptionTransactionStatsParams) (GetSubscriptionTransactionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionTransactionStats, arg.SubscriptionID, arg.UserID)
	var i GetSubscriptionTransactionStatsRow
	err := row.Scan(&i.LinkedCount, &i.TotalSpent)
	return i, err
}

const listSubscriptionTransactions = `-- name: ListSubscriptionTransactions :many
SELECT t.id, t.name, t.amount, t.type, t.transaction_date, t.category_id,
       COALESCE(c.name, t.category_name)::text AS category_name, t.budget_id, b.name AS budget_name,
       t.subscription_id, s.name AS subscription_name, t.notes, t.created_at
FROM financial_horizon_transactions t
LEFT JOIN financial_horizon_categories c ON t.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON t.budget_id = b.id
LEFT JOIN financial_horizon_subscriptions s ON t.subscription_id = s.id
WHERE t.user_id = $1 AND t.subscription_id = $2
ORDER BY t.transaction_date DESC, t.id DESC
`

type ListSubscriptionTransactionsParams struct {
	UserID         int64
	SubscriptionID sql.NullInt64
}

type ListSubscriptionTransactionsRow struct {
	ID               int64
	Name             string
	Amount           float64
	Type             string
	TransactionDate  time.Time
	CategoryID       sql.NullInt64
	CategoryName     string
	BudgetID         sql.NullInt64
	BudgetName       sql.NullString
	SubscriptionID   sql.NullInt64
	SubscriptionName sql.NullString
	Notes            sql.NullString
	CreatedAt        time.Time
}

func (q *Queries) ListSubscriptionTransactions(ctx context.Context, arg ListSubscriptionTransactionsParams) ([]ListSubscriptionTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionTransactions, arg.UserID, arg.SubscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionTransactionsRow
	for rows.Next() {
		var i ListSubscriptionTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.SubscriptionID,
			&i.SubscriptionName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT s.id, s.name, s.amount, s.billing_cycle, s.billing_day, s.renewal_date, s.status,
       s.category_id, c.name AS category_name, s.budget_id, b.name AS budget_name, s.deduction_id, s.notes, s.created_at, s.updated_at,
       COALESCE(COUNT(t.id), 0)::bigint AS linked_count,
       COALESCE(SUM(t.amount), 0)::double precision AS total_spent
FROM financial_horizon_subscriptions s
LEFT JOIN financial_horizon_categories c ON s.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON s.budget_id = b.id
LEFT JOIN financial_horizon_transactions t ON t.subscription_id = s.id
WHERE s.user_id = $1
GROUP BY s.id, c.name, b.name
ORDER BY CASE WHEN s.status = 'active' THEN 1 WHEN s.status = 'paused' THEN 2 ELSE 3 END, s.created_at DESC, s.id DESC
`

type ListSubscriptionsRow struct {
	ID           int64
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	CategoryName sql.NullString
	BudgetID     sql.NullInt64
	BudgetName   sql.NullString
	DeductionID  sql.NullInt64
	Notes        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LinkedCount  int64
	TotalSpent   float64
}

func (q *Queries) ListSubscriptions(ctx context.Context, userID int64) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.BillingCycle,
			&i.BillingDay,
			&i.RenewalDate,
			&i.Status,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.DeductionID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkedCount,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE financial_horizon_subscriptions
SET name = $1, amount = $2, billing_cycle = $3, billing_day = $4, renewal_date = $5, status = $6,
    category_id = $7, budget_id = $8, deduction_id = $9, notes = $10, updated_at = CURRENT_TIMESTAMP
WHERE id = $11 AND user_id = $12
RETURNING id, name, amount, billing_cycle, billing_day, renewal_date, status, category_id, budget_id, deduction_id, notes, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        sql.NullString
	ID           int64
	UserID       int64
}

type UpdateSubscriptionRow struct {
	ID           int64
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (UpdateSubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, updateSubscription,
		arg.Name,
		arg.Amount,
		arg.BillingCycle,
		arg.BillingDay,
		arg.RenewalDate,
		arg.Status,
		arg.CategoryID,
		arg.BudgetID,
		arg.DeductionID,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i UpdateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.BillingCycle,
		&i.BillingDay,
		&i.RenewalDate,
		&i.Status,
		&i.CategoryID,
		&i.BudgetID,
		&i.DeductionID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
