// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo, front_tire_pressure_pillion, rear_tire_pressure_pillion)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo, front_tire_pressure_pillion, rear_tire_pressure_pillion
`

type CreateVehicleParams struct {
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

type CreateVehicleRow struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (CreateVehicleRow, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.Name,
		arg.IsActive,
		arg.FrontTirePressureSolo,
		arg.RearTirePressureSolo,
		arg.FrontTirePressurePillion,
		arg.RearTirePressurePillion,
	)
	var i CreateVehicleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :execrows
DELETE FROM vehicles WHERE id=$1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVehicle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVehicleAirFill = `-- name: DeleteVehicleAirFill :execrows
DELETE FROM vehicle_air_fills WHERE id=$1 AND vehicle_id=$2 AND user_id=$3
`

type DeleteVehicleAirFillParams struct {
	ID        int64
	VehicleID int64
	UserID    int64
}

func (q *Queries) DeleteVehicleAirFill(ctx context.Context, arg DeleteVehicleAirFillParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVehicleAirFill, arg.ID, arg.VehicleID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVehicleFuelFillup = `-- name: DeleteVehicleFuelFillup :execrows
DELETE FROM vehicle_fuel_fillups WHERE id=$1 AND vehicle_id=$2 AND user_id=$3
`

type DeleteVehicleFuelFillupParams struct {
	ID        int64
	VehicleID int64
	UserID    int64
}

func (q *Queries) DeleteVehicleFuelFillup(ctx context.Context, arg DeleteVehicleFuelFillupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVehicleFuelFillup, arg.ID, arg.VehicleID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo,
front_tire_pressure_pillion, rear_tire_pressure_pillion FROM vehicles WHERE id=$1
`

type GetVehicleRow struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) GetVehicle(ctx context.Context, id int64) (GetVehicleRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicle, id)
	var i GetVehicleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}

const getVehicleForUpdate = `-- name: GetVehicleForUpdate :one
SELECT name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo,
front_tire_pressure_pillion, rear_tire_pressure_pillion FROM vehicles WHERE id=$1
`

type GetVehicleForUpdateRow struct {
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) GetVehicleForUpdate(ctx context.Context, id int64) (GetVehicleForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleForUpdate, id)
	var i GetVehicleForUpdateRow
	err := row.Scan(
		&i.Name,
		&i.IsActive,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}

const getVehicleHistoryHeader = `-- name: GetVehicleHistoryHeader :one
SELECT name, front_tire_pressure_solo, rear_tire_pressure_solo,
front_tire_pressure_pillion, rear_tire_pressure_pillion FROM vehicles WHERE id=$1
`

type GetVehicleHistoryHeaderRow struct {
	Name                     string
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) GetVehicleHistoryHeader(ctx context.Context, id int64) (GetVehicleHistoryHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleHistoryHeader, id)
	var i GetVehicleHistoryHeaderRow
	err := row.Scan(
		&i.Name,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}

const listFuelItems = `-- name: ListFuelItems :many
SELECT fuel_type,fill_type,quantity,unit_price,total_cost FROM vehicle_fuel_items WHERE fillup_id=$1 ORDER BY id
`

type ListFuelItemsRow struct {
	FuelType  string
	FillType  string
	Quantity  float64
	UnitPrice float64
	TotalCost float64
}

func (q *Queries) ListFuelItems(ctx context.Context, fillupID int64) ([]ListFuelItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFuelItems, fillupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelItemsRow
	for rows.Next() {
		var i ListFuelItemsRow
		if err := rows.Scan(
			&i.FuelType,
			&i.FillType,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceAttachments = `-- name: ListMaintenanceAttachments :many
SELECT id,file_name,content_type,size_bytes,created_at FROM vehicle_maintenance_attachments
WHERE maintenance_record_id=$1 AND user_id=$2 ORDER BY created_at ASC
`

type ListMaintenanceAttachmentsParams struct {
	MaintenanceRecordID int64
	UserID              int64
}

type ListMaintenanceAttachmentsRow struct {
	ID          int64
	FileName    string
	ContentType string
	SizeBytes   int64
	CreatedAt   time.Time
}

func (q *Queries) ListMaintenanceAttachments(ctx context.Context, arg ListMaintenanceAttachmentsParams) ([]ListMaintenanceAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceAttachments, arg.MaintenanceRecordID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceAttachmentsRow
	for rows.Next() {
		var i ListMaintenanceAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleAirFills = `-- name: ListVehicleAirFills :many
SELECT id,filled_at FROM vehicle_air_fills WHERE vehicle_id=$1 AND user_id=$2 ORDER BY filled_at DESC,id DESC
`

type ListVehicleAirFillsParams struct {
	VehicleID int64
	UserID    int64
}

type ListVehicleAirFillsRow struct {
	ID       int64
	FilledAt time.Time
}

func (q *Queries) ListVehicleAirFills(ctx context.Context, arg ListVehicleAirFillsParams) ([]ListVehicleAirFillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleAirFills, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleAirFillsRow
	for rows.Next() {
		var i ListVehicleAirFillsRow
		if err := rows.Scan(&i.ID, &i.FilledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleFuelFillups = `-- name: ListVehicleFuelFillups :many
SELECT id,odometer_km,filled_at,station_name,notes FROM vehicle_fuel_fillups
WHERE vehicle_id=$1 AND user_id=$2 ORDER BY filled_at DESC,id DESC
`

type ListVehicleFuelFillupsParams struct {
	VehicleID int64
	UserID    int64
}

type ListVehicleFuelFillupsRow struct {
	ID          int64
	OdometerKm  float64
	FilledAt    time.Time
	StationName sql.NullString
	Notes       sql.NullString
}

func (q *Queries) ListVehicleFuelFillups(ctx context.Context, arg ListVehicleFuelFillupsParams) ([]ListVehicleFuelFillupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleFuelFillups, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleFuelFillupsRow
	for rows.Next() {
		var i ListVehicleFuelFillupsRow
		if err := rows.Scan(
			&i.ID,
			&i.OdometerKm,
			&i.FilledAt,
			&i.StationName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleMaintenanceRecords = `-- name: ListVehicleMaintenanceRecords :many
SELECT id,category,title,amount,occurred_at,odometer_km,provider_name,notes
FROM vehicle_maintenance_records WHERE vehicle_id=$1 AND user_id=$2 ORDER BY occurred_at DESC,id DESC
`

type ListVehicleMaintenanceRecordsParams struct {
	VehicleID int64
	UserID    int64
}

type ListVehicleMaintenanceRecordsRow struct {
	ID           int64
	Category     string
	Title        string
	Amount       float64
	OccurredAt   time.Time
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        sql.NullString
}

func (q *Queries) ListVehicleMaintenanceRecords(ctx context.Context, arg ListVehicleMaintenanceRecordsParams) ([]ListVehicleMaintenanceRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleMaintenanceRecords, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleMaintenanceRecordsRow
	for rows.Next() {
		var i ListVehicleMaintenanceRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Title,
			&i.Amount,
			&i.OccurredAt,
			&i.OdometerKm,
			&i.ProviderName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, name FROM vehicles ORDER BY id ASC
`

type ListVehiclesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListVehicles(ctx context.Context) ([]ListVehiclesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles SET name=$1, is_active=$2, front_tire_pressure_solo=$3, rear_tire_pressure_solo=$4,
front_tire_pressure_pillion=$5, rear_tire_pressure_pillion=$6, updated_at=now()
WHERE id=$7 RETURNING id, name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo,
front_tire_pressure_pillion, rear_tire_pressure_pillion
`

type UpdateVehicleParams struct {
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
	ID                       int64
}

type UpdateVehicleRow struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (UpdateVehicleRow, error) {
	row := q.db.QueryRowContext(ctx, updateVehicle,
		arg.Name,
		arg.IsActive,
		arg.FrontTirePressureSolo,
		arg.RearTirePressureSolo,
		arg.FrontTirePressurePillion,
		arg.RearTirePressurePillion,
		arg.ID,
	)
	var i UpdateVehicleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}

const updateVehicleTirePressure = `-- name: UpdateVehicleTirePressure :one
UPDATE vehicles SET front_tire_pressure_solo=$1, rear_tire_pressure_solo=$2,
front_tire_pressure_pillion=$3, rear_tire_pressure_pillion=$4, updated_at=now()
WHERE id=$5 RETURNING id, name, is_active, front_tire_pressure_solo, rear_tire_pressure_solo,
front_tire_pressure_pillion, rear_tire_pressure_pillion
`

type UpdateVehicleTirePressureParams struct {
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
	ID                       int64
}

type UpdateVehicleTirePressureRow struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

func (q *Queries) UpdateVehicleTirePressure(ctx context.Context, arg UpdateVehicleTirePressureParams) (UpdateVehicleTirePressureRow, error) {
	row := q.db.QueryRowContext(ctx, updateVehicleTirePressure,
		arg.FrontTirePressureSolo,
		arg.RearTirePressureSolo,
		arg.FrontTirePressurePillion,
		arg.RearTirePressurePillion,
		arg.ID,
	)
	var i UpdateVehicleTirePressureRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.FrontTirePressureSolo,
		&i.RearTirePressureSolo,
		&i.FrontTirePressurePillion,
		&i.RearTirePressurePillion,
	)
	return i, err
}
