// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_air.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAirFillNotification = `-- name: CreateAirFillNotification :one
INSERT INTO notifications (user_id, source, title, body, target_path, priority, metadata)
VALUES ($1, 'Garage', $2, $3, '/garage', 1, jsonb_build_object('vehicle_id', $4::bigint)) RETURNING id
`

type CreateAirFillNotificationParams struct {
	UserID  int64
	Title   string
	Body    sql.NullString
	Column4 int64
}

func (q *Queries) CreateAirFillNotification(ctx context.Context, arg CreateAirFillNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAirFillNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Column4,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVehicleAirFill = `-- name: CreateVehicleAirFill :one
INSERT INTO vehicle_air_fills (vehicle_id, user_id) VALUES ($1, $2) RETURNING filled_at
`

type CreateVehicleAirFillParams struct {
	VehicleID int64
	UserID    int64
}

func (q *Queries) CreateVehicleAirFill(ctx context.Context, arg CreateVehicleAirFillParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, createVehicleAirFill, arg.VehicleID, arg.UserID)
	var filled_at time.Time
	err := row.Scan(&filled_at)
	return filled_at, err
}

const linkAirFillReminder = `-- name: LinkAirFillReminder :exec
UPDATE vehicle_air_fills SET reminder_notification_id = $1 WHERE id = $2
`

type LinkAirFillReminderParams struct {
	ReminderNotificationID sql.NullInt64
	ID                     int64
}

func (q *Queries) LinkAirFillReminder(ctx context.Context, arg LinkAirFillReminderParams) error {
	_, err := q.db.ExecContext(ctx, linkAirFillReminder, arg.ReminderNotificationID, arg.ID)
	return err
}

const listDueAirFillReminders = `-- name: ListDueAirFillReminders :many
SELECT id FROM vehicle_air_fills WHERE reminder_notification_id IS NULL
AND filled_at <= NOW() - INTERVAL '30 days' LIMIT 100
`

func (q *Queries) ListDueAirFillReminders(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listDueAirFillReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestVehicleAirFills = `-- name: ListLatestVehicleAirFills :many
SELECT DISTINCT ON (vehicle_id) vehicle_id, filled_at FROM vehicle_air_fills
WHERE user_id = $1 ORDER BY vehicle_id, filled_at DESC, id DESC
`

type ListLatestVehicleAirFillsRow struct {
	VehicleID int64
	FilledAt  time.Time
}

func (q *Queries) ListLatestVehicleAirFills(ctx context.Context, userID int64) ([]ListLatestVehicleAirFillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestVehicleAirFills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestVehicleAirFillsRow
	for rows.Next() {
		var i ListLatestVehicleAirFillsRow
		if err := rows.Scan(&i.VehicleID, &i.FilledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueAirFillReminder = `-- name: LockDueAirFillReminder :one
SELECT vehicle_air_fills.user_id, vehicle_air_fills.vehicle_id, vehicles.name
FROM vehicle_air_fills JOIN vehicles ON vehicles.id = vehicle_air_fills.vehicle_id
WHERE vehicle_air_fills.id = $1 AND vehicle_air_fills.reminder_notification_id IS NULL
AND vehicle_air_fills.filled_at <= NOW() - INTERVAL '30 days' FOR UPDATE
`

type LockDueAirFillReminderRow struct {
	UserID    int64
	VehicleID int64
	Name      string
}

func (q *Queries) LockDueAirFillReminder(ctx context.Context, id int64) (LockDueAirFillReminderRow, error) {
	row := q.db.QueryRowContext(ctx, lockDueAirFillReminder, id)
	var i LockDueAirFillReminderRow
	err := row.Scan(&i.UserID, &i.VehicleID, &i.Name)
	return i, err
}

const vehicleExists = `-- name: VehicleExists :one
SELECT EXISTS(SELECT 1 FROM vehicles WHERE id = $1)
`

func (q *Queries) VehicleExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, vehicleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
