// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CreditCard struct {
	ID        int64
	Name      string
	Link      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FinancialHorizonBudget struct {
	ID              int64
	UserID          int64
	Name            string
	AllocatedAmount float64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type FinancialHorizonCategory struct {
	ID        int64
	UserID    sql.NullInt64
	Name      string
	Icon      string
	Color     string
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FinancialHorizonConfig struct {
	UserID     int64
	BaseAmount float64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type FinancialHorizonDeduction struct {
	ID        int64
	UserID    int64
	Name      string
	Category  string
	Amount    float64
	DueDay    sql.NullInt16
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  sql.NullInt64
}

type FinancialHorizonSubscription struct {
	ID           int64
	UserID       int64
	Name         string
	Amount       float64
	BillingCycle string
	BillingDay   sql.NullInt32
	RenewalDate  sql.NullTime
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type FinancialHorizonTransaction struct {
	ID              int64
	UserID          int64
	Name            string
	Amount          float64
	TransactionDate time.Time
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	Notes           sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Type            string
	SubscriptionID  sql.NullInt64
}

type GymExerciseSet struct {
	ID                 int64
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             *float64
	CreatedAt          time.Time
}

type GymReminderDelivery struct {
	ID             int64
	UserID         int64
	ReminderDate   time.Time
	NotificationID int64
	CreatedAt      time.Time
}

type GymVisit struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GymVisitExercise struct {
	ID         int64
	GymVisitID int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type MealPlan struct {
	ID         int64
	UserID     int64
	Date       time.Time
	Name       string
	MealTimeID sql.NullInt64
	StartTime  sql.NullTime
	EndTime    sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsConsumed bool
}

type MealTime struct {
	ID        int64
	UserID    sql.NullInt64
	Name      string
	StartTime time.Time
	EndTime   time.Time
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Meditation struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type NextMonthPurchase struct {
	ID          int64
	UserID      int64
	TargetMonth time.Time
	Name        string
	Price       float64
	Url         sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Notification struct {
	ID          int64
	UserID      int64
	Source      string
	Title       string
	Body        sql.NullString
	TargetPath  sql.NullString
	Priority    int16
	Metadata    json.RawMessage
	ReadAt      sql.NullTime
	DismissedAt sql.NullTime
	CreatedAt   time.Time
}

type Sport struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Trip struct {
	ID          int64
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserProfile struct {
	UserID      int64
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserSession struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Vehicle struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
	FrontTirePressureSolo    *float64
	RearTirePressureSolo     *float64
	FrontTirePressurePillion *float64
	RearTirePressurePillion  *float64
}

type VehicleAirFill struct {
	ID                     int64
	VehicleID              int64
	UserID                 int64
	FilledAt               time.Time
	ReminderNotificationID sql.NullInt64
	CreatedAt              time.Time
}

type VehicleFuelFillup struct {
	ID          int64
	VehicleID   int64
	UserID      int64
	OdometerKm  float64
	FilledAt    time.Time
	StationName sql.NullString
	Notes       sql.NullString
	CreatedAt   time.Time
}

type VehicleFuelItem struct {
	ID        int64
	FillupID  int64
	FuelType  string
	FillType  string
	Quantity  float64
	UnitPrice float64
	TotalCost float64
	CreatedAt time.Time
}

type VehicleMaintenanceAttachment struct {
	ID                  int64
	MaintenanceRecordID int64
	UserID              int64
	StorageKey          string
	FileName            string
	ContentType         string
	SizeBytes           int64
	CreatedAt           time.Time
}

type VehicleMaintenanceRecord struct {
	ID           int64
	VehicleID    int64
	UserID       int64
	Category     string
	Title        string
	Amount       float64
	OccurredAt   time.Time
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
