// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_air.sql

package query

import (
	"context"
	"time"
)

const createVehicleAirFill = `-- name: CreateVehicleAirFill :one
INSERT INTO vehicle_air_fills (vehicle_id, user_id) VALUES ($1, $2) RETURNING filled_at
`

type CreateVehicleAirFillParams struct {
	VehicleID int64
	UserID    int64
}

func (q *Queries) CreateVehicleAirFill(ctx context.Context, arg CreateVehicleAirFillParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, createVehicleAirFill, arg.VehicleID, arg.UserID)
	var filled_at time.Time
	err := row.Scan(&filled_at)
	return filled_at, err
}

const listLatestVehicleAirFills = `-- name: ListLatestVehicleAirFills :many
SELECT DISTINCT ON (vehicle_id) vehicle_id, filled_at FROM vehicle_air_fills
WHERE user_id = $1 ORDER BY vehicle_id, filled_at DESC, id DESC
`

type ListLatestVehicleAirFillsRow struct {
	VehicleID int64
	FilledAt  time.Time
}

func (q *Queries) ListLatestVehicleAirFills(ctx context.Context, userID int64) ([]ListLatestVehicleAirFillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestVehicleAirFills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestVehicleAirFillsRow
	for rows.Next() {
		var i ListLatestVehicleAirFillsRow
		if err := rows.Scan(&i.VehicleID, &i.FilledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vehicleExists = `-- name: VehicleExists :one
SELECT EXISTS(SELECT 1 FROM vehicles WHERE id = $1)
`

func (q *Queries) VehicleExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, vehicleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
