// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_attachments.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaintenanceAttachment = `-- name: CreateMaintenanceAttachment :one
INSERT INTO vehicle_maintenance_attachments (maintenance_record_id,user_id,storage_key,file_name,content_type,size_bytes)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,file_name,content_type,size_bytes,created_at
`

type CreateMaintenanceAttachmentParams struct {
	MaintenanceRecordID int64
	UserID              int64
	StorageKey          string
	FileName            string
	ContentType         string
	SizeBytes           int64
}

type CreateMaintenanceAttachmentRow struct {
	ID          int64
	FileName    string
	ContentType string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateMaintenanceAttachment(ctx context.Context, arg CreateMaintenanceAttachmentParams) (CreateMaintenanceAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceAttachment,
		arg.MaintenanceRecordID,
		arg.UserID,
		arg.StorageKey,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i CreateMaintenanceAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaintenanceAttachment = `-- name: DeleteMaintenanceAttachment :exec
DELETE FROM vehicle_maintenance_attachments WHERE id=$1 AND user_id=$2
`

type DeleteMaintenanceAttachmentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteMaintenanceAttachment(ctx context.Context, arg DeleteMaintenanceAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceAttachment, arg.ID, arg.UserID)
	return err
}

const getMaintenanceAttachmentKey = `-- name: GetMaintenanceAttachmentKey :one
SELECT a.storage_key FROM vehicle_maintenance_attachments a
JOIN vehicle_maintenance_records r ON r.id=a.maintenance_record_id
WHERE a.id=$1 AND a.maintenance_record_id=$2 AND r.vehicle_id=$3 AND a.user_id=$4
`

type GetMaintenanceAttachmentKeyParams struct {
	ID                  int64
	MaintenanceRecordID int64
	VehicleID           int64
	UserID              int64
}

func (q *Queries) GetMaintenanceAttachmentKey(ctx context.Context, arg GetMaintenanceAttachmentKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, getMaintenanceAttachmentKey,
		arg.ID,
		arg.MaintenanceRecordID,
		arg.VehicleID,
		arg.UserID,
	)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const listMaintenanceAttachmentKeys = `-- name: ListMaintenanceAttachmentKeys :many
SELECT storage_key FROM vehicle_maintenance_attachments WHERE maintenance_record_id=$1 AND user_id=$2
`

type ListMaintenanceAttachmentKeysParams struct {
	MaintenanceRecordID int64
	UserID              int64
}

func (q *Queries) ListMaintenanceAttachmentKeys(ctx context.Context, arg ListMaintenanceAttachmentKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMaintenanceAttachmentKeys, arg.MaintenanceRecordID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownsMaintenanceRecord = `-- name: OwnsMaintenanceRecord :one
SELECT EXISTS(SELECT 1 FROM vehicle_maintenance_records WHERE id=$1 AND vehicle_id=$2 AND user_id=$3)
`

type OwnsMaintenanceRecordParams struct {
	ID        int64
	VehicleID int64
	UserID    int64
}

func (q *Queries) OwnsMaintenanceRecord(ctx context.Context, arg OwnsMaintenanceRecordParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsMaintenanceRecord, arg.ID, arg.VehicleID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
