// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle_fuel.sql

package query

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFuelFillup = `-- name: CreateFuelFillup :one
INSERT INTO vehicle_fuel_fillups (vehicle_id,user_id,odometer_km,filled_at,station_name,notes)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id
`

type CreateFuelFillupParams struct {
	VehicleID   int64
	UserID      int64
	OdometerKm  float64
	FilledAt    pgtype.Timestamptz
	StationName sql.NullString
	Notes       pgtype.Text
}

func (q *Queries) CreateFuelFillup(ctx context.Context, arg CreateFuelFillupParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFuelFillup,
		arg.VehicleID,
		arg.UserID,
		arg.OdometerKm,
		arg.FilledAt,
		arg.StationName,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createFuelItem = `-- name: CreateFuelItem :exec
INSERT INTO vehicle_fuel_items (fillup_id,fuel_type,fill_type,quantity,unit_price,total_cost)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateFuelItemParams struct {
	FillupID  int64
	FuelType  string
	FillType  string
	Quantity  float64
	UnitPrice float64
	TotalCost float64
}

func (q *Queries) CreateFuelItem(ctx context.Context, arg CreateFuelItemParams) error {
	_, err := q.db.Exec(ctx, createFuelItem,
		arg.FillupID,
		arg.FuelType,
		arg.FillType,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalCost,
	)
	return err
}

const deleteFuelItems = `-- name: DeleteFuelItems :exec
DELETE FROM vehicle_fuel_items WHERE fillup_id=$1
`

func (q *Queries) DeleteFuelItems(ctx context.Context, fillupID int64) error {
	_, err := q.db.Exec(ctx, deleteFuelItems, fillupID)
	return err
}

const getMaxFuelOdometer = `-- name: GetMaxFuelOdometer :one
SELECT COALESCE(MAX(odometer_km), -1)::double precision FROM vehicle_fuel_fillups WHERE vehicle_id=$1
`

func (q *Queries) GetMaxFuelOdometer(ctx context.Context, vehicleID int64) (float64, error) {
	row := q.db.QueryRow(ctx, getMaxFuelOdometer, vehicleID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAverageFuelEconomyEntries = `-- name: ListAverageFuelEconomyEntries :many
SELECT i.fuel_type, f.odometer_km, i.fill_type, i.quantity FROM vehicle_fuel_fillups f
JOIN vehicle_fuel_items i ON i.fillup_id=f.id
WHERE f.vehicle_id=$1 AND f.user_id=$2 ORDER BY i.fuel_type, f.filled_at, f.id
`

type ListAverageFuelEconomyEntriesParams struct {
	VehicleID int64
	UserID    int64
}

type ListAverageFuelEconomyEntriesRow struct {
	FuelType   string
	OdometerKm float64
	FillType   string
	Quantity   float64
}

func (q *Queries) ListAverageFuelEconomyEntries(ctx context.Context, arg ListAverageFuelEconomyEntriesParams) ([]ListAverageFuelEconomyEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAverageFuelEconomyEntries, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAverageFuelEconomyEntriesRow
	for rows.Next() {
		var i ListAverageFuelEconomyEntriesRow
		if err := rows.Scan(
			&i.FuelType,
			&i.OdometerKm,
			&i.FillType,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelEconomyEntries = `-- name: ListFuelEconomyEntries :many
SELECT f.odometer_km, i.fill_type, i.quantity FROM vehicle_fuel_fillups f
JOIN vehicle_fuel_items i ON i.fillup_id=f.id
WHERE f.vehicle_id=$1 AND i.fuel_type=$2 ORDER BY f.filled_at, f.id
`

type ListFuelEconomyEntriesParams struct {
	VehicleID int64
	FuelType  string
}

type ListFuelEconomyEntriesRow struct {
	OdometerKm float64
	FillType   string
	Quantity   float64
}

func (q *Queries) ListFuelEconomyEntries(ctx context.Context, arg ListFuelEconomyEntriesParams) ([]ListFuelEconomyEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFuelEconomyEntries, arg.VehicleID, arg.FuelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelEconomyEntriesRow
	for rows.Next() {
		var i ListFuelEconomyEntriesRow
		if err := rows.Scan(&i.OdometerKm, &i.FillType, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFuelFillup = `-- name: LockFuelFillup :one
SELECT 1 FROM vehicle_fuel_fillups WHERE id=$1 AND vehicle_id=$2 AND user_id=$3 FOR UPDATE
`

type LockFuelFillupParams struct {
	ID        int64
	VehicleID int64
	UserID    int64
}

func (q *Queries) LockFuelFillup(ctx context.Context, arg LockFuelFillupParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockFuelFillup, arg.ID, arg.VehicleID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateFuelFillup = `-- name: UpdateFuelFillup :exec
UPDATE vehicle_fuel_fillups SET odometer_km=$1,filled_at=$2,station_name=$3,notes=$4 WHERE id=$5
`

type UpdateFuelFillupParams struct {
	OdometerKm  float64
	FilledAt    pgtype.Timestamptz
	StationName sql.NullString
	Notes       pgtype.Text
	ID          int64
}

func (q *Queries) UpdateFuelFillup(ctx context.Context, arg UpdateFuelFillupParams) error {
	_, err := q.db.Exec(ctx, updateFuelFillup,
		arg.OdometerKm,
		arg.FilledAt,
		arg.StationName,
		arg.Notes,
		arg.ID,
	)
	return err
}
