// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_maintenance.sql

package query

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaintenanceRecord = `-- name: CreateMaintenanceRecord :one
INSERT INTO vehicle_maintenance_records (vehicle_id,user_id,category,title,amount,occurred_at,odometer_km,provider_name,notes)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id,category,title,amount,occurred_at,odometer_km,provider_name,notes
`

type CreateMaintenanceRecordParams struct {
	VehicleID    int64
	UserID       int64
	Category     string
	Title        string
	Amount       float64
	OccurredAt   pgtype.Timestamptz
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        pgtype.Text
}

type CreateMaintenanceRecordRow struct {
	ID           int64
	Category     string
	Title        string
	Amount       float64
	OccurredAt   pgtype.Timestamptz
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        pgtype.Text
}

func (q *Queries) CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (CreateMaintenanceRecordRow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecord,
		arg.VehicleID,
		arg.UserID,
		arg.Category,
		arg.Title,
		arg.Amount,
		arg.OccurredAt,
		arg.OdometerKm,
		arg.ProviderName,
		arg.Notes,
	)
	var i CreateMaintenanceRecordRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Amount,
		&i.OccurredAt,
		&i.OdometerKm,
		&i.ProviderName,
		&i.Notes,
	)
	return i, err
}

const deleteMaintenanceRecord = `-- name: DeleteMaintenanceRecord :execrows
DELETE FROM vehicle_maintenance_records WHERE id=$1 AND vehicle_id=$2 AND user_id=$3
`

type DeleteMaintenanceRecordParams struct {
	ID        int64
	VehicleID int64
	UserID    int64
}

func (q *Queries) DeleteMaintenanceRecord(ctx context.Context, arg DeleteMaintenanceRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenanceRecord, arg.ID, arg.VehicleID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaintenanceRecord = `-- name: UpdateMaintenanceRecord :one
UPDATE vehicle_maintenance_records
SET category=$1,title=$2,amount=$3,occurred_at=$4,odometer_km=$5,provider_name=$6,notes=$7,updated_at=CURRENT_TIMESTAMP
WHERE id=$8 AND vehicle_id=$9 AND user_id=$10
RETURNING id,category,title,amount,occurred_at,odometer_km,provider_name,notes
`

type UpdateMaintenanceRecordParams struct {
	Category     string
	Title        string
	Amount       float64
	OccurredAt   pgtype.Timestamptz
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        pgtype.Text
	ID           int64
	VehicleID    int64
	UserID       int64
}

type UpdateMaintenanceRecordRow struct {
	ID           int64
	Category     string
	Title        string
	Amount       float64
	OccurredAt   pgtype.Timestamptz
	OdometerKm   *float64
	ProviderName sql.NullString
	Notes        pgtype.Text
}

func (q *Queries) UpdateMaintenanceRecord(ctx context.Context, arg UpdateMaintenanceRecordParams) (UpdateMaintenanceRecordRow, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceRecord,
		arg.Category,
		arg.Title,
		arg.Amount,
		arg.OccurredAt,
		arg.OdometerKm,
		arg.ProviderName,
		arg.Notes,
		arg.ID,
		arg.VehicleID,
		arg.UserID,
	)
	var i UpdateMaintenanceRecordRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Amount,
		&i.OccurredAt,
		&i.OdometerKm,
		&i.ProviderName,
		&i.Notes,
	)
	return i, err
}
