// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package query

import (
	"context"
)

const getDisplayName = `-- name: GetDisplayName :one
SELECT display_name FROM user_profiles WHERE user_id=$1
`

func (q *Queries) GetDisplayName(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getDisplayName, userID)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const saveDisplayName = `-- name: SaveDisplayName :exec
INSERT INTO user_profiles (user_id,display_name) VALUES ($1,$2)
ON CONFLICT (user_id) DO UPDATE SET display_name=EXCLUDED.display_name,updated_at=NOW()
`

type SaveDisplayNameParams struct {
	UserID      int64
	DisplayName string
}

func (q *Queries) SaveDisplayName(ctx context.Context, arg SaveDisplayNameParams) error {
	_, err := q.db.Exec(ctx, saveDisplayName, arg.UserID, arg.DisplayName)
	return err
}
