// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gym.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVisit = `-- name: AddVisit :one
INSERT INTO gym_visits (user_id) VALUES ($1) RETURNING id
`

func (q *Queries) AddVisit(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, addVisit, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addVisitOnDate = `-- name: AddVisitOnDate :one
INSERT INTO gym_visits (user_id, created_at) VALUES ($1, $2) RETURNING id
`

type AddVisitOnDateParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddVisitOnDate(ctx context.Context, arg AddVisitOnDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, addVisitOnDate, arg.UserID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO gym_visit_exercises (gym_visit_id,name) VALUES ($1,$2) RETURNING id,name
`

type CreateExerciseParams struct {
	GymVisitID int64
	Name       string
}

type CreateExerciseRow struct {
	ID   int64
	Name string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (CreateExerciseRow, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.GymVisitID, arg.Name)
	var i CreateExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSet = `-- name: CreateSet :one
INSERT INTO gym_exercise_sets (gym_visit_exercise_id,set_number,reps,weight)
VALUES ($1,$2,$3,$4) RETURNING id,set_number,reps,weight
`

type CreateSetParams struct {
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             *float64
}

type CreateSetRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (CreateSetRow, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.GymVisitExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
	)
	var i CreateSetRow
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
	)
	return i, err
}

const deleteVisit = `-- name: DeleteVisit :execrows
DELETE FROM gym_visits WHERE id=$1 AND user_id=$2
`

type DeleteVisitParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteVisit(ctx context.Context, arg DeleteVisitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVisit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVisit = `-- name: GetVisit :one
SELECT g.id, g.created_at, w.start_time, w.end_time,
    w.duration_seconds, w.calories_burned
FROM gym_visits AS g
LEFT JOIN fitness_workouts AS w ON w.id = g.fitness_workout_id AND w.user_id = g.user_id
WHERE g.id = $1 AND g.user_id = $2
`

type GetVisitParams struct {
	ID     int64
	UserID int64
}

type GetVisitRow struct {
	ID              int64
	CreatedAt       pgtype.Timestamptz
	StartTime       pgtype.Timestamptz
	EndTime         pgtype.Timestamptz
	DurationSeconds *float64
	CaloriesBurned  *float64
}

func (q *Queries) GetVisit(ctx context.Context, arg GetVisitParams) (GetVisitRow, error) {
	row := q.db.QueryRow(ctx, getVisit, arg.ID, arg.UserID)
	var i GetVisitRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.DurationSeconds,
		&i.CaloriesBurned,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id,name FROM gym_visit_exercises WHERE gym_visit_id=$1 ORDER BY id ASC
`

type ListExercisesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListExercises(ctx context.Context, gymVisitID int64) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, gymVisitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT id,set_number,reps,weight FROM gym_exercise_sets WHERE gym_visit_exercise_id=$1 ORDER BY set_number ASC
`

type ListSetsRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) ListSets(ctx context.Context, gymVisitExerciseID int64) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets, gymVisitExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsRow
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisits = `-- name: ListVisits :many
SELECT id,created_at FROM gym_visits WHERE user_id=$1 ORDER BY created_at DESC,id DESC
`

type ListVisitsRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVisits(ctx context.Context, userID int64) ([]ListVisitsRow, error) {
	rows, err := q.db.Query(ctx, listVisits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsRow
	for rows.Next() {
		var i ListVisitsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewSessions = `-- name: OverviewSessions :many
SELECT w.start_time, w.duration_seconds::double precision AS duration_seconds
FROM fitness_workouts w
JOIN workout_activity_types a ON a.id = w.activity_type_id
WHERE w.user_id = $1 AND a.raw_value = 50
    AND w.start_time >= $2 AND w.start_time <= $3
    AND EXISTS (
        SELECT 1 FROM gym_visits g WHERE g.user_id = w.user_id AND g.created_at <= $3
        AND (g.created_at AT TIME ZONE 'Asia/Kolkata')::date =
            (w.start_time AT TIME ZONE 'Asia/Kolkata')::date
    )
`

type OverviewSessionsParams struct {
	UserID      int64
	StartTime   pgtype.Timestamptz
	StartTime_2 pgtype.Timestamptz
}

type OverviewSessionsRow struct {
	StartTime       pgtype.Timestamptz
	DurationSeconds float64
}

func (q *Queries) OverviewSessions(ctx context.Context, arg OverviewSessionsParams) ([]OverviewSessionsRow, error) {
	rows, err := q.db.Query(ctx, overviewSessions, arg.UserID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverviewSessionsRow
	for rows.Next() {
		var i OverviewSessionsRow
		if err := rows.Scan(&i.StartTime, &i.DurationSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewVisits = `-- name: OverviewVisits :many
SELECT g.id, g.created_at,
    COUNT(s.id)::bigint AS sets,
    COALESCE(SUM(s.reps * s.weight), 0)::double precision AS volume,
    COUNT(s.id) FILTER (WHERE s.weight IS NULL)::bigint AS unweighted_sets
FROM gym_visits g
LEFT JOIN gym_visit_exercises e ON e.gym_visit_id = g.id
LEFT JOIN gym_exercise_sets s ON s.gym_visit_exercise_id = e.id
WHERE g.user_id = $1 AND g.created_at <= $2
GROUP BY g.id
ORDER BY g.created_at DESC, g.id DESC
`

type OverviewVisitsParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type OverviewVisitsRow struct {
	ID             int64
	CreatedAt      pgtype.Timestamptz
	Sets           int64
	Volume         float64
	UnweightedSets int64
}

func (q *Queries) OverviewVisits(ctx context.Context, arg OverviewVisitsParams) ([]OverviewVisitsRow, error) {
	rows, err := q.db.Query(ctx, overviewVisits, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverviewVisitsRow
	for rows.Next() {
		var i OverviewVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Sets,
			&i.Volume,
			&i.UnweightedSets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visitExists = `-- name: VisitExists :one
SELECT EXISTS(SELECT 1 FROM gym_visits WHERE id=$1 AND user_id=$2)
`

type VisitExistsParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) VisitExists(ctx context.Context, arg VisitExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, visitExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const visitToday = `-- name: VisitToday :one
SELECT id FROM gym_visits WHERE user_id=$1 AND created_at >= $2 AND created_at < $3 ORDER BY created_at DESC LIMIT 1
`

type VisitTodayParams struct {
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) VisitToday(ctx context.Context, arg VisitTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, visitToday, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}
