// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gym.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVisit = `-- name: AddVisit :one
INSERT INTO gym_visits DEFAULT VALUES RETURNING id
`

func (q *Queries) AddVisit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, addVisit)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO gym_visit_exercises (gym_visit_id,name) VALUES ($1,$2) RETURNING id,name
`

type CreateExerciseParams struct {
	GymVisitID int64
	Name       string
}

type CreateExerciseRow struct {
	ID   int64
	Name string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (CreateExerciseRow, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.GymVisitID, arg.Name)
	var i CreateExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSet = `-- name: CreateSet :one
INSERT INTO gym_exercise_sets (gym_visit_exercise_id,set_number,reps,weight)
VALUES ($1,$2,$3,$4) RETURNING id,set_number,reps,weight
`

type CreateSetParams struct {
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             *float64
}

type CreateSetRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (CreateSetRow, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.GymVisitExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
	)
	var i CreateSetRow
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
	)
	return i, err
}

const deleteVisit = `-- name: DeleteVisit :execrows
DELETE FROM gym_visits WHERE id=$1
`

func (q *Queries) DeleteVisit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVisit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deliveryExists = `-- name: DeliveryExists :one
SELECT EXISTS(SELECT 1 FROM gym_reminder_deliveries WHERE user_id=$1 AND reminder_date=($2::text)::date)
`

type DeliveryExistsParams struct {
	UserID  int64
	Column2 string
}

func (q *Queries) DeliveryExists(ctx context.Context, arg DeliveryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, deliveryExists, arg.UserID, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExercises = `-- name: ListExercises :many
SELECT id,name FROM gym_visit_exercises WHERE gym_visit_id=$1 ORDER BY id ASC
`

type ListExercisesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListExercises(ctx context.Context, gymVisitID int64) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, gymVisitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT id,set_number,reps,weight FROM gym_exercise_sets WHERE gym_visit_exercise_id=$1 ORDER BY set_number ASC
`

type ListSetsRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) ListSets(ctx context.Context, gymVisitExerciseID int64) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets, gymVisitExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsRow
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisits = `-- name: ListVisits :many
SELECT id,created_at FROM gym_visits ORDER BY created_at DESC,id DESC
`

type ListVisitsRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVisits(ctx context.Context) ([]ListVisitsRow, error) {
	rows, err := q.db.Query(ctx, listVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsRow
	for rows.Next() {
		var i ListVisitsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDelivery = `-- name: RecordDelivery :exec
INSERT INTO gym_reminder_deliveries (user_id,reminder_date,notification_id)
VALUES ($1,($2::text)::date,$3)
`

type RecordDeliveryParams struct {
	UserID         int64
	Column2        string
	NotificationID int64
}

func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordDelivery, arg.UserID, arg.Column2, arg.NotificationID)
	return err
}

const visitExists = `-- name: VisitExists :one
SELECT EXISTS(SELECT 1 FROM gym_visits WHERE id=$1)
`

func (q *Queries) VisitExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, visitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const visitToday = `-- name: VisitToday :one
SELECT id FROM gym_visits WHERE created_at >= $1 AND created_at < $2 ORDER BY created_at DESC LIMIT 1
`

type VisitTodayParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) VisitToday(ctx context.Context, arg VisitTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, visitToday, arg.CreatedAt, arg.CreatedAt_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}
