// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gym.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVisit = `-- name: AddVisit :one
INSERT INTO gym_visits (user_id) VALUES ($1) RETURNING id
`

func (q *Queries) AddVisit(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, addVisit, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addVisitOnDate = `-- name: AddVisitOnDate :one
INSERT INTO gym_visits (user_id, created_at) VALUES ($1, $2) RETURNING id
`

type AddVisitOnDateParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddVisitOnDate(ctx context.Context, arg AddVisitOnDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, addVisitOnDate, arg.UserID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO gym_visit_exercises (gym_visit_id,name,exercise_catalog_id)
VALUES ($1,$2,$3) RETURNING id,name,exercise_catalog_id
`

type CreateExerciseParams struct {
	GymVisitID        int64
	Name              string
	ExerciseCatalogID *string
}

type CreateExerciseRow struct {
	ID                int64
	Name              string
	ExerciseCatalogID *string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (CreateExerciseRow, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.GymVisitID, arg.Name, arg.ExerciseCatalogID)
	var i CreateExerciseRow
	err := row.Scan(&i.ID, &i.Name, &i.ExerciseCatalogID)
	return i, err
}

const createSet = `-- name: CreateSet :one
INSERT INTO gym_exercise_sets (gym_visit_exercise_id,set_number,reps,weight)
VALUES ($1,$2,$3,$4) RETURNING id,set_number,reps,weight
`

type CreateSetParams struct {
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             *float64
}

type CreateSetRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (CreateSetRow, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.GymVisitExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
	)
	var i CreateSetRow
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :execrows
DELETE FROM gym_visit_exercises AS e
USING gym_visits AS v
WHERE e.id = $1
  AND e.gym_visit_id = $2
  AND v.id = e.gym_visit_id
  AND v.user_id = $3
`

type DeleteExerciseParams struct {
	ExerciseID int64
	VisitID    int64
	UserID     int64
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExercise, arg.ExerciseID, arg.VisitID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExerciseSets = `-- name: DeleteExerciseSets :exec
DELETE FROM gym_exercise_sets WHERE gym_visit_exercise_id=$1
`

func (q *Queries) DeleteExerciseSets(ctx context.Context, gymVisitExerciseID int64) error {
	_, err := q.db.Exec(ctx, deleteExerciseSets, gymVisitExerciseID)
	return err
}

const deleteVisit = `-- name: DeleteVisit :execrows
DELETE FROM gym_visits WHERE id=$1 AND user_id=$2
`

type DeleteVisitParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteVisit(ctx context.Context, arg DeleteVisitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVisit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCatalogExercise = `-- name: GetCatalogExercise :one
SELECT id, name, equipment, data FROM exercise_catalog WHERE id=$1
`

type GetCatalogExerciseRow struct {
	ID        string
	Name      string
	Equipment *string
	Data      []byte
}

func (q *Queries) GetCatalogExercise(ctx context.Context, id string) (GetCatalogExerciseRow, error) {
	row := q.db.QueryRow(ctx, getCatalogExercise, id)
	var i GetCatalogExerciseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Equipment,
		&i.Data,
	)
	return i, err
}

const getVisit = `-- name: GetVisit :one
SELECT g.id, g.created_at, w.start_time, w.end_time,
    w.duration_seconds, w.calories_burned,
    CASE WHEN w.id IS NULL THEN FALSE ELSE TRUE END AS synced_from_apple_watch
FROM gym_visits AS g
LEFT JOIN fitness_workouts AS w ON w.id = g.fitness_workout_id AND w.user_id = g.user_id
WHERE g.id = $1 AND g.user_id = $2
`

type GetVisitParams struct {
	ID     int64
	UserID int64
}

type GetVisitRow struct {
	ID                   int64
	CreatedAt            pgtype.Timestamptz
	StartTime            pgtype.Timestamptz
	EndTime              pgtype.Timestamptz
	DurationSeconds      *float64
	CaloriesBurned       *float64
	SyncedFromAppleWatch bool
}

func (q *Queries) GetVisit(ctx context.Context, arg GetVisitParams) (GetVisitRow, error) {
	row := q.db.QueryRow(ctx, getVisit, arg.ID, arg.UserID)
	var i GetVisitRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.DurationSeconds,
		&i.CaloriesBurned,
		&i.SyncedFromAppleWatch,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT e.id, e.name, e.exercise_catalog_id, c.name AS catalog_name, c.equipment, c.data
FROM gym_visit_exercises e
LEFT JOIN exercise_catalog c ON c.id = e.exercise_catalog_id
WHERE e.gym_visit_id=$1 ORDER BY e.id ASC
`

type ListExercisesRow struct {
	ID                int64
	Name              string
	ExerciseCatalogID *string
	CatalogName       *string
	Equipment         *string
	Data              []byte
}

func (q *Queries) ListExercises(ctx context.Context, gymVisitID int64) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, gymVisitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExerciseCatalogID,
			&i.CatalogName,
			&i.Equipment,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT id,set_number,reps,weight FROM gym_exercise_sets WHERE gym_visit_exercise_id=$1 ORDER BY set_number ASC
`

type ListSetsRow struct {
	ID        int64
	SetNumber int16
	Reps      int16
	Weight    *float64
}

func (q *Queries) ListSets(ctx context.Context, gymVisitExerciseID int64) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets, gymVisitExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsRow
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisits = `-- name: ListVisits :many
SELECT id,created_at FROM gym_visits WHERE user_id=$1 ORDER BY created_at DESC,id DESC
`

type ListVisitsRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVisits(ctx context.Context, userID int64) ([]ListVisitsRow, error) {
	rows, err := q.db.Query(ctx, listVisits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsRow
	for rows.Next() {
		var i ListVisitsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewSessions = `-- name: OverviewSessions :many
SELECT w.start_time, w.duration_seconds::double precision AS duration_seconds
FROM fitness_workouts w
JOIN workout_activity_types a ON a.id = w.activity_type_id
WHERE w.user_id = $1 AND a.raw_value = 50
    AND w.start_time >= $2 AND w.start_time <= $3
    AND EXISTS (
        SELECT 1 FROM gym_visits g WHERE g.user_id = w.user_id AND g.created_at <= $3
        AND (g.created_at AT TIME ZONE 'Asia/Kolkata')::date =
            (w.start_time AT TIME ZONE 'Asia/Kolkata')::date
    )
`

type OverviewSessionsParams struct {
	UserID      int64
	StartTime   pgtype.Timestamptz
	StartTime_2 pgtype.Timestamptz
}

type OverviewSessionsRow struct {
	StartTime       pgtype.Timestamptz
	DurationSeconds float64
}

func (q *Queries) OverviewSessions(ctx context.Context, arg OverviewSessionsParams) ([]OverviewSessionsRow, error) {
	rows, err := q.db.Query(ctx, overviewSessions, arg.UserID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverviewSessionsRow
	for rows.Next() {
		var i OverviewSessionsRow
		if err := rows.Scan(&i.StartTime, &i.DurationSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewVisits = `-- name: OverviewVisits :many
SELECT g.id, g.created_at,
    COUNT(s.id)::bigint AS sets,
    COALESCE(SUM(s.reps * s.weight), 0)::double precision AS volume,
    COUNT(s.id) FILTER (WHERE s.weight IS NULL)::bigint AS unweighted_sets
FROM gym_visits g
LEFT JOIN gym_visit_exercises e ON e.gym_visit_id = g.id
LEFT JOIN gym_exercise_sets s ON s.gym_visit_exercise_id = e.id
WHERE g.user_id = $1 AND g.created_at <= $2
GROUP BY g.id
ORDER BY g.created_at DESC, g.id DESC
`

type OverviewVisitsParams struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type OverviewVisitsRow struct {
	ID             int64
	CreatedAt      pgtype.Timestamptz
	Sets           int64
	Volume         float64
	UnweightedSets int64
}

func (q *Queries) OverviewVisits(ctx context.Context, arg OverviewVisitsParams) ([]OverviewVisitsRow, error) {
	rows, err := q.db.Query(ctx, overviewVisits, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverviewVisitsRow
	for rows.Next() {
		var i OverviewVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Sets,
			&i.Volume,
			&i.UnweightedSets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rememberExerciseAlias = `-- name: RememberExerciseAlias :exec
INSERT INTO exercise_aliases (user_id, normalized_alias, exercise_catalog_id)
VALUES ($1,$2,$3)
ON CONFLICT (user_id, normalized_alias)
DO UPDATE SET exercise_catalog_id = EXCLUDED.exercise_catalog_id
`

type RememberExerciseAliasParams struct {
	UserID            int64
	NormalizedAlias   string
	ExerciseCatalogID string
}

func (q *Queries) RememberExerciseAlias(ctx context.Context, arg RememberExerciseAliasParams) error {
	_, err := q.db.Exec(ctx, rememberExerciseAlias, arg.UserID, arg.NormalizedAlias, arg.ExerciseCatalogID)
	return err
}

const searchExerciseCatalog = `-- name: SearchExerciseCatalog :many
SELECT c.id, c.name, c.equipment, c.data,
    CASE WHEN c.normalized_name = $1::text THEN 'exact'
         WHEN a.exercise_catalog_id IS NOT NULL THEN 'alias'
         ELSE 'suggested' END::text AS match_type
FROM exercise_catalog c
LEFT JOIN exercise_aliases a ON a.exercise_catalog_id = c.id
    AND a.user_id = $2 AND a.normalized_alias = $1::text
WHERE c.normalized_name = $1::text
   OR a.exercise_catalog_id IS NOT NULL
   OR c.normalized_name % $1::text
   OR strpos(c.normalized_name, $1::text) > 0
ORDER BY CASE WHEN c.normalized_name = $1::text THEN 0
              WHEN a.exercise_catalog_id IS NOT NULL THEN 1 ELSE 2 END,
    similarity(c.normalized_name, $1::text) DESC, c.name, c.id
LIMIT 8
`

type SearchExerciseCatalogParams struct {
	Search string
	UserID int64
}

type SearchExerciseCatalogRow struct {
	ID        string
	Name      string
	Equipment *string
	Data      []byte
	MatchType string
}

func (q *Queries) SearchExerciseCatalog(ctx context.Context, arg SearchExerciseCatalogParams) ([]SearchExerciseCatalogRow, error) {
	rows, err := q.db.Query(ctx, searchExerciseCatalog, arg.Search, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchExerciseCatalogRow
	for rows.Next() {
		var i SearchExerciseCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Equipment,
			&i.Data,
			&i.MatchType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE gym_visit_exercises AS e
SET name = $1, exercise_catalog_id = $2, updated_at = NOW()
FROM gym_visits AS v
WHERE e.id = $3 AND e.gym_visit_id = $4
  AND v.id = e.gym_visit_id AND v.user_id = $5
RETURNING e.id
`

type UpdateExerciseParams struct {
	Name              string
	ExerciseCatalogID *string
	ExerciseID        int64
	VisitID           int64
	UserID            int64
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.Name,
		arg.ExerciseCatalogID,
		arg.ExerciseID,
		arg.VisitID,
		arg.UserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const visitExists = `-- name: VisitExists :one
SELECT EXISTS(SELECT 1 FROM gym_visits WHERE id=$1 AND user_id=$2)
`

type VisitExistsParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) VisitExists(ctx context.Context, arg VisitExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, visitExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const visitToday = `-- name: VisitToday :one
SELECT id FROM gym_visits WHERE user_id=$1 AND created_at >= $2 AND created_at < $3 ORDER BY created_at DESC LIMIT 1
`

type VisitTodayParams struct {
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) VisitToday(ctx context.Context, arg VisitTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, visitToday, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}
