-- workout_activity_types must be created first because
-- fitness_workouts references it.

CREATE TABLE workout_activity_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_value INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT workout_activity_types_raw_value_key
        UNIQUE (raw_value)
);

CREATE INDEX idx_workout_activity_types_raw_value
    ON workout_activity_types (raw_value);


CREATE TABLE fitness_activity_rings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_date DATE NOT NULL,

    move_calories NUMERIC(8, 2) NOT NULL DEFAULT 0,
    move_calories_goal NUMERIC(8, 2) NOT NULL DEFAULT 0,

    exercise_minutes INTEGER NOT NULL DEFAULT 0,
    exercise_minutes_goal INTEGER NOT NULL DEFAULT 0,

    stand_hours INTEGER NOT NULL DEFAULT 0,
    stand_hours_goal INTEGER NOT NULL DEFAULT 0,

    steps_count INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fitness_activity_rings_summary_date_key
        UNIQUE (summary_date),

    CONSTRAINT fitness_activity_rings_move_calories_check
        CHECK (move_calories >= 0),

    CONSTRAINT fitness_activity_rings_move_calories_goal_check
        CHECK (move_calories_goal >= 0),

    CONSTRAINT fitness_activity_rings_exercise_minutes_check
        CHECK (exercise_minutes >= 0),

    CONSTRAINT fitness_activity_rings_exercise_minutes_goal_check
        CHECK (exercise_minutes_goal >= 0),

    CONSTRAINT fitness_activity_rings_stand_hours_check
        CHECK (stand_hours >= 0),

    CONSTRAINT fitness_activity_rings_stand_hours_goal_check
        CHECK (stand_hours_goal >= 0),

    CONSTRAINT fitness_activity_rings_steps_count_check
        CHECK (steps_count >= 0)
);

CREATE INDEX idx_fitness_activity_rings_summary_date
    ON fitness_activity_rings (summary_date DESC);


CREATE TABLE fitness_workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,

    activity_type_id INTEGER NOT NULL,

    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,

    duration_seconds NUMERIC(10, 3) NOT NULL,

    calories_burned NUMERIC(8, 2),
    distance_meters NUMERIC(10, 2),

    metadata JSONB DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fitness_workouts_uuid_key
        UNIQUE (uuid),

    CONSTRAINT fitness_workouts_activity_type_id_fkey
        FOREIGN KEY (activity_type_id)
        REFERENCES workout_activity_types (id)
        ON DELETE RESTRICT,

    CONSTRAINT fitness_workouts_duration_seconds_check
        CHECK (duration_seconds >= 0),

    CONSTRAINT fitness_workouts_calories_burned_check
        CHECK (
            calories_burned IS NULL
            OR calories_burned >= 0
        ),

    CONSTRAINT fitness_workouts_distance_meters_check
        CHECK (
            distance_meters IS NULL
            OR distance_meters >= 0
        )
);

CREATE INDEX idx_fitness_workouts_uuid
    ON fitness_workouts (uuid);

CREATE INDEX idx_fitness_workouts_start_time
    ON fitness_workouts (start_time DESC);

CREATE INDEX idx_fitness_workouts_activity_type_id
    ON fitness_workouts (activity_type_id);