// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMeditation = `-- name: AddMeditation :exec
INSERT INTO meditations DEFAULT VALUES
`

func (q *Queries) AddMeditation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, addMeditation)
	return err
}

const addSport = `-- name: AddSport :exec
INSERT INTO sports (name) VALUES ($1)
`

func (q *Queries) AddSport(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, addSport, name)
	return err
}

const meditatedToday = `-- name: MeditatedToday :one
SELECT EXISTS(SELECT 1 FROM meditations WHERE created_at >= $1 AND created_at < $2)
`

type MeditatedTodayParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) MeditatedToday(ctx context.Context, arg MeditatedTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, meditatedToday, arg.CreatedAt, arg.CreatedAt_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
