// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearNotifications = `-- name: ClearNotifications :exec
UPDATE notifications SET dismissed_at=NOW() WHERE user_id=$1 AND dismissed_at IS NULL
`

func (q *Queries) ClearNotifications(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearNotifications, userID)
	return err
}

const createAirFillReminder = `-- name: CreateAirFillReminder :one
INSERT INTO notifications (user_id,source,title,body,target_path,priority,metadata)
VALUES ($1,'Garage','Time to check ' || $3 || '''s air','It has been 30 days since you last filled air in ' || $3 || '.','/garage',1,jsonb_build_object('vehicle_id',$2::bigint))
RETURNING id
`

type CreateAirFillReminderParams struct {
	UserID  int64
	Column2 int64
	Column3 *string
}

func (q *Queries) CreateAirFillReminder(ctx context.Context, arg CreateAirFillReminderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAirFillReminder, arg.UserID, arg.Column2, arg.Column3)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGymReminder = `-- name: CreateGymReminder :one
INSERT INTO notifications (user_id,source,title,body,target_path,priority,metadata)
VALUES ($1,'Gym reminder','Time for the gym','Your 3:30 PM gym reminder. Mark your visit when you are done.','/gym-visits',1,jsonb_build_object('reminder_date',$2::text))
RETURNING id
`

type CreateGymReminderParams struct {
	UserID  int64
	Column2 string
}

func (q *Queries) CreateGymReminder(ctx context.Context, arg CreateGymReminderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGymReminder, arg.UserID, arg.Column2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const dismissGymReminder = `-- name: DismissGymReminder :exec
UPDATE notifications SET dismissed_at=NOW() WHERE id=$1
`

func (q *Queries) DismissGymReminder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dismissGymReminder, id)
	return err
}

const dismissNotification = `-- name: DismissNotification :execrows
UPDATE notifications SET dismissed_at=NOW() WHERE id=$1 AND user_id=$2 AND dismissed_at IS NULL
`

type DismissNotificationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DismissNotification(ctx context.Context, arg DismissNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissNotification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const gymReminderExists = `-- name: GymReminderExists :one
SELECT EXISTS(SELECT 1 FROM notifications WHERE id=$1 AND user_id=$2 AND source='Gym reminder' AND dismissed_at IS NULL)
`

type GymReminderExistsParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GymReminderExists(ctx context.Context, arg GymReminderExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, gymReminderExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id,source,title,body,target_path,priority,created_at FROM notifications
WHERE user_id=$1 AND dismissed_at IS NULL ORDER BY created_at DESC,id DESC LIMIT $2
`

type ListNotificationsParams struct {
	UserID int64
	Limit  int32
}

type ListNotificationsRow struct {
	ID         int64
	Source     string
	Title      string
	Body       *string
	TargetPath *string
	Priority   int16
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.TargetPath,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
