// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deductions.sql

package query

import (
	"context"
	"database/sql"
)

const createDeduction = `-- name: CreateDeduction :one
INSERT INTO financial_horizon_deductions (user_id, name, category, amount, due_day, is_active, budget_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, category, amount, due_day, is_active, budget_id
`

type CreateDeductionParams struct {
	UserID   int64
	Name     string
	Category string
	Amount   float64
	DueDay   sql.NullInt16
	IsActive bool
	BudgetID sql.NullInt64
}

type CreateDeductionRow struct {
	ID       int64
	Name     string
	Category string
	Amount   float64
	DueDay   sql.NullInt16
	IsActive bool
	BudgetID sql.NullInt64
}

func (q *Queries) CreateDeduction(ctx context.Context, arg CreateDeductionParams) (CreateDeductionRow, error) {
	row := q.db.QueryRowContext(ctx, createDeduction,
		arg.UserID,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.DueDay,
		arg.IsActive,
		arg.BudgetID,
	)
	var i CreateDeductionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.DueDay,
		&i.IsActive,
		&i.BudgetID,
	)
	return i, err
}

const deleteDeduction = `-- name: DeleteDeduction :execrows
DELETE FROM financial_horizon_deductions WHERE id = $1 AND user_id = $2
`

type DeleteDeductionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteDeduction(ctx context.Context, arg DeleteDeductionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeduction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDeductions = `-- name: ListDeductions :many
SELECT id, name, category, amount, due_day, is_active, budget_id
FROM financial_horizon_deductions WHERE user_id = $1
ORDER BY is_active DESC, created_at DESC, id DESC
`

type ListDeductionsRow struct {
	ID       int64
	Name     string
	Category string
	Amount   float64
	DueDay   sql.NullInt16
	IsActive bool
	BudgetID sql.NullInt64
}

func (q *Queries) ListDeductions(ctx context.Context, userID int64) ([]ListDeductionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeductions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeductionsRow
	for rows.Next() {
		var i ListDeductionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.DueDay,
			&i.IsActive,
			&i.BudgetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeduction = `-- name: UpdateDeduction :one
UPDATE financial_horizon_deductions
SET name = $1, category = $2, amount = $3, due_day = $4, is_active = $5, budget_id = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $7 AND user_id = $8
RETURNING id, name, category, amount, due_day, is_active, budget_id
`

type UpdateDeductionParams struct {
	Name     string
	Category string
	Amount   float64
	DueDay   sql.NullInt16
	IsActive bool
	BudgetID sql.NullInt64
	ID       int64
	UserID   int64
}

type UpdateDeductionRow struct {
	ID       int64
	Name     string
	Category string
	Amount   float64
	DueDay   sql.NullInt16
	IsActive bool
	BudgetID sql.NullInt64
}

func (q *Queries) UpdateDeduction(ctx context.Context, arg UpdateDeductionParams) (UpdateDeductionRow, error) {
	row := q.db.QueryRowContext(ctx, updateDeduction,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.DueDay,
		arg.IsActive,
		arg.BudgetID,
		arg.ID,
		arg.UserID,
	)
	var i UpdateDeductionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.DueDay,
		&i.IsActive,
		&i.BudgetID,
	)
	return i, err
}
