// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: horizon.sql

package query

import (
	"context"
)

const getHorizonConfig = `-- name: GetHorizonConfig :one
SELECT base_amount, currency FROM financial_horizon_configs WHERE user_id = $1
`

type GetHorizonConfigRow struct {
	BaseAmount float64
	Currency   string
}

func (q *Queries) GetHorizonConfig(ctx context.Context, userID int64) (GetHorizonConfigRow, error) {
	row := q.db.QueryRow(ctx, getHorizonConfig, userID)
	var i GetHorizonConfigRow
	err := row.Scan(&i.BaseAmount, &i.Currency)
	return i, err
}

const upsertHorizonConfig = `-- name: UpsertHorizonConfig :exec
INSERT INTO financial_horizon_configs (user_id, base_amount, currency, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE
SET base_amount = EXCLUDED.base_amount, currency = EXCLUDED.currency, updated_at = CURRENT_TIMESTAMP
`

type UpsertHorizonConfigParams struct {
	UserID     int64
	BaseAmount float64
	Currency   string
}

func (q *Queries) UpsertHorizonConfig(ctx context.Context, arg UpsertHorizonConfigParams) error {
	_, err := q.db.Exec(ctx, upsertHorizonConfig, arg.UserID, arg.BaseAmount, arg.Currency)
	return err
}
