// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package query

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredTransactions = `-- name: CountFilteredTransactions :one
SELECT COUNT(*) FROM financial_horizon_transactions t
WHERE t.user_id = $1
  AND ($2::text = '' OR t.type = $2)
  AND ($3::text = '' OR LOWER(t.name) LIKE $3 OR LOWER(t.notes) LIKE $3)
`

type CountFilteredTransactionsParams struct {
	UserID  int64
	Column2 string
	Column3 string
}

func (q *Queries) CountFilteredTransactions(ctx context.Context, arg CountFilteredTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredTransactions, arg.UserID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO financial_horizon_transactions (user_id, name, amount, type, transaction_date, category_id, category_name, budget_id, subscription_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, amount, type, transaction_date, category_id, category_name, budget_id, subscription_id, notes, created_at
`

type CreateTransactionParams struct {
	UserID          int64
	Name            string
	Amount          float64
	Type            string
	TransactionDate pgtype.Timestamptz
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	SubscriptionID  sql.NullInt64
	Notes           pgtype.Text
}

type CreateTransactionRow struct {
	ID              int64
	Name            string
	Amount          float64
	Type            string
	TransactionDate pgtype.Timestamptz
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	SubscriptionID  sql.NullInt64
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.CategoryID,
		arg.CategoryName,
		arg.BudgetID,
		arg.SubscriptionID,
		arg.Notes,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.CategoryID,
		&i.CategoryName,
		&i.BudgetID,
		&i.SubscriptionID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM financial_horizon_transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscriptionName = `-- name: GetSubscriptionName :one
SELECT name FROM financial_horizon_subscriptions WHERE id = $1 AND user_id = $2
`

type GetSubscriptionNameParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSubscriptionName(ctx context.Context, arg GetSubscriptionNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getSubscriptionName, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserCategoryName = `-- name: GetUserCategoryName :one
SELECT name FROM financial_horizon_categories WHERE id = $1 AND (user_id IS NULL OR user_id = $2)
`

type GetUserCategoryNameParams struct {
	ID     int64
	UserID sql.NullInt64
}

func (q *Queries) GetUserCategoryName(ctx context.Context, arg GetUserCategoryNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserCategoryName, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listFilteredTransactions = `-- name: ListFilteredTransactions :many
SELECT t.id, t.name, t.amount, t.type, t.transaction_date, t.category_id,
       COALESCE(c.name, t.category_name)::text AS category_name, t.budget_id, b.name AS budget_name,
       t.subscription_id, s.name AS subscription_name, t.notes, t.created_at
FROM financial_horizon_transactions t
LEFT JOIN financial_horizon_categories c ON t.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON t.budget_id = b.id
LEFT JOIN financial_horizon_subscriptions s ON t.subscription_id = s.id
WHERE t.user_id = $1
  AND ($2::text = '' OR t.type = $2)
  AND ($3::text = '' OR LOWER(t.name) LIKE $3 OR LOWER(t.notes) LIKE $3)
ORDER BY t.transaction_date DESC, t.id DESC LIMIT $4 OFFSET $5
`

type ListFilteredTransactionsParams struct {
	UserID  int64
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

type ListFilteredTransactionsRow struct {
	ID               int64
	Name             string
	Amount           float64
	Type             string
	TransactionDate  pgtype.Timestamptz
	CategoryID       sql.NullInt64
	CategoryName     string
	BudgetID         sql.NullInt64
	BudgetName       sql.NullString
	SubscriptionID   sql.NullInt64
	SubscriptionName sql.NullString
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListFilteredTransactions(ctx context.Context, arg ListFilteredTransactionsParams) ([]ListFilteredTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listFilteredTransactions,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilteredTransactionsRow
	for rows.Next() {
		var i ListFilteredTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.SubscriptionID,
			&i.SubscriptionName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilteredTransactionsLegacy = `-- name: ListFilteredTransactionsLegacy :many
SELECT t.id, t.name, t.amount, t.type, t.transaction_date, t.category_id,
       COALESCE(c.name, t.category_name)::text AS category_name, t.budget_id, b.name AS budget_name,
       NULL::bigint AS subscription_id, NULL::text AS subscription_name, t.notes, t.created_at
FROM financial_horizon_transactions t
LEFT JOIN financial_horizon_categories c ON t.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON t.budget_id = b.id
WHERE t.user_id = $1
  AND ($2::text = '' OR t.type = $2)
  AND ($3::text = '' OR LOWER(t.name) LIKE $3 OR LOWER(t.notes) LIKE $3)
ORDER BY t.transaction_date DESC, t.id DESC LIMIT $4 OFFSET $5
`

type ListFilteredTransactionsLegacyParams struct {
	UserID  int64
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

type ListFilteredTransactionsLegacyRow struct {
	ID               int64
	Name             string
	Amount           float64
	Type             string
	TransactionDate  pgtype.Timestamptz
	CategoryID       sql.NullInt64
	CategoryName     string
	BudgetID         sql.NullInt64
	BudgetName       sql.NullString
	SubscriptionID   sql.NullInt64
	SubscriptionName pgtype.Text
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListFilteredTransactionsLegacy(ctx context.Context, arg ListFilteredTransactionsLegacyParams) ([]ListFilteredTransactionsLegacyRow, error) {
	rows, err := q.db.Query(ctx, listFilteredTransactionsLegacy,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilteredTransactionsLegacyRow
	for rows.Next() {
		var i ListFilteredTransactionsLegacyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.SubscriptionID,
			&i.SubscriptionName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT t.id, t.name, t.amount, t.type, t.transaction_date, t.category_id,
       COALESCE(c.name, t.category_name)::text AS category_name, t.budget_id, b.name AS budget_name,
       t.subscription_id, s.name AS subscription_name, t.notes, t.created_at
FROM financial_horizon_transactions t
LEFT JOIN financial_horizon_categories c ON t.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON t.budget_id = b.id
LEFT JOIN financial_horizon_subscriptions s ON t.subscription_id = s.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.id DESC LIMIT $2
`

type ListRecentTransactionsParams struct {
	UserID int64
	Limit  int32
}

type ListRecentTransactionsRow struct {
	ID               int64
	Name             string
	Amount           float64
	Type             string
	TransactionDate  pgtype.Timestamptz
	CategoryID       sql.NullInt64
	CategoryName     string
	BudgetID         sql.NullInt64
	BudgetName       sql.NullString
	SubscriptionID   sql.NullInt64
	SubscriptionName sql.NullString
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListRecentTransactions(ctx context.Context, arg ListRecentTransactionsParams) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsRow
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.SubscriptionID,
			&i.SubscriptionName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactionsLegacy = `-- name: ListRecentTransactionsLegacy :many
SELECT t.id, t.name, t.amount, t.type, t.transaction_date, t.category_id,
       COALESCE(c.name, t.category_name)::text AS category_name, t.budget_id, b.name AS budget_name,
       NULL::bigint AS subscription_id, NULL::text AS subscription_name, t.notes, t.created_at
FROM financial_horizon_transactions t
LEFT JOIN financial_horizon_categories c ON t.category_id = c.id
LEFT JOIN financial_horizon_budgets b ON t.budget_id = b.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.id DESC LIMIT $2
`

type ListRecentTransactionsLegacyParams struct {
	UserID int64
	Limit  int32
}

type ListRecentTransactionsLegacyRow struct {
	ID               int64
	Name             string
	Amount           float64
	Type             string
	TransactionDate  pgtype.Timestamptz
	CategoryID       sql.NullInt64
	CategoryName     string
	BudgetID         sql.NullInt64
	BudgetName       sql.NullString
	SubscriptionID   sql.NullInt64
	SubscriptionName pgtype.Text
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListRecentTransactionsLegacy(ctx context.Context, arg ListRecentTransactionsLegacyParams) ([]ListRecentTransactionsLegacyRow, error) {
	rows, err := q.db.Query(ctx, listRecentTransactionsLegacy, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsLegacyRow
	for rows.Next() {
		var i ListRecentTransactionsLegacyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.CategoryID,
			&i.CategoryName,
			&i.BudgetID,
			&i.BudgetName,
			&i.SubscriptionID,
			&i.SubscriptionName,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE financial_horizon_transactions
SET name = $1, amount = $2, type = $3, transaction_date = $4, category_id = $5, category_name = $6,
    budget_id = $7, subscription_id = $8, notes = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $10 AND user_id = $11
RETURNING id, name, amount, type, transaction_date, category_id, category_name, budget_id, subscription_id, notes, created_at
`

type UpdateTransactionParams struct {
	Name            string
	Amount          float64
	Type            string
	TransactionDate pgtype.Timestamptz
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	SubscriptionID  sql.NullInt64
	Notes           pgtype.Text
	ID              int64
	UserID          int64
}

type UpdateTransactionRow struct {
	ID              int64
	Name            string
	Amount          float64
	Type            string
	TransactionDate pgtype.Timestamptz
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	SubscriptionID  sql.NullInt64
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.CategoryID,
		arg.CategoryName,
		arg.BudgetID,
		arg.SubscriptionID,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.CategoryID,
		&i.CategoryName,
		&i.BudgetID,
		&i.SubscriptionID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
