// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreditCard struct {
	ID        int64
	Name      string
	Link      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FinancialHorizonBudget struct {
	ID              int64
	UserID          int64
	Name            string
	AllocatedAmount pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FinancialHorizonCategory struct {
	ID        int64
	UserID    sql.NullInt64
	Name      string
	Icon      string
	Color     string
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FinancialHorizonConfig struct {
	UserID     int64
	BaseAmount pgtype.Numeric
	Currency   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type FinancialHorizonDeduction struct {
	ID        int64
	UserID    int64
	Name      string
	Category  string
	Amount    pgtype.Numeric
	DueDay    pgtype.Int2
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	BudgetID  sql.NullInt64
}

type FinancialHorizonSubscription struct {
	ID           int64
	UserID       int64
	Name         string
	Amount       pgtype.Numeric
	BillingCycle string
	BillingDay   pgtype.Int4
	RenewalDate  pgtype.Timestamptz
	Status       string
	CategoryID   sql.NullInt64
	BudgetID     sql.NullInt64
	DeductionID  sql.NullInt64
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type FinancialHorizonTransaction struct {
	ID              int64
	UserID          int64
	Name            string
	Amount          pgtype.Numeric
	TransactionDate pgtype.Timestamptz
	CategoryID      sql.NullInt64
	CategoryName    string
	BudgetID        sql.NullInt64
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Type            string
	SubscriptionID  sql.NullInt64
}

type GymExerciseSet struct {
	ID                 int64
	GymVisitExerciseID int64
	SetNumber          int16
	Reps               int16
	Weight             pgtype.Numeric
	CreatedAt          pgtype.Timestamptz
}

type GymReminderDelivery struct {
	ID             int64
	UserID         int64
	ReminderDate   pgtype.Date
	NotificationID int64
	CreatedAt      pgtype.Timestamptz
}

type GymVisit struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GymVisitExercise struct {
	ID         int64
	GymVisitID int64
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type MealPlan struct {
	ID         int64
	UserID     int64
	Date       pgtype.Date
	Name       string
	MealTimeID sql.NullInt64
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsConsumed bool
}

type MealTime struct {
	ID        int64
	UserID    sql.NullInt64
	Name      string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Meditation struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type NextMonthPurchase struct {
	ID          int64
	UserID      int64
	TargetMonth pgtype.Date
	Name        string
	Price       pgtype.Numeric
	Url         pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID          int64
	UserID      int64
	Source      string
	Title       string
	Body        pgtype.Text
	TargetPath  sql.NullString
	Priority    int16
	Metadata    []byte
	ReadAt      pgtype.Timestamptz
	DismissedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Sport struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Trip struct {
	ID          int64
	Name        string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserProfile struct {
	UserID      int64
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserSession struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Vehicle struct {
	ID                       int64
	Name                     string
	IsActive                 bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	FrontTirePressureSolo    pgtype.Numeric
	RearTirePressureSolo     pgtype.Numeric
	FrontTirePressurePillion pgtype.Numeric
	RearTirePressurePillion  pgtype.Numeric
}

type VehicleAirFill struct {
	ID                     int64
	VehicleID              int64
	UserID                 int64
	FilledAt               pgtype.Timestamptz
	ReminderNotificationID sql.NullInt64
	CreatedAt              pgtype.Timestamptz
}

type VehicleFuelFillup struct {
	ID          int64
	VehicleID   int64
	UserID      int64
	OdometerKm  pgtype.Numeric
	FilledAt    pgtype.Timestamptz
	StationName sql.NullString
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type VehicleFuelItem struct {
	ID        int64
	FillupID  int64
	FuelType  string
	FillType  string
	Quantity  pgtype.Numeric
	UnitPrice pgtype.Numeric
	TotalCost pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type VehicleMaintenanceAttachment struct {
	ID                  int64
	MaintenanceRecordID int64
	UserID              int64
	StorageKey          string
	FileName            string
	ContentType         string
	SizeBytes           int64
	CreatedAt           pgtype.Timestamptz
}

type VehicleMaintenanceRecord struct {
	ID           int64
	VehicleID    int64
	UserID       int64
	Category     string
	Title        string
	Amount       pgtype.Numeric
	OccurredAt   pgtype.Timestamptz
	OdometerKm   pgtype.Numeric
	ProviderName sql.NullString
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
