// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (user_id,token_hash,expires_at) VALUES ($1,$2,$3)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE token_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
SELECT id,password_hash FROM users WHERE username=$1
`

type LoginUserRow struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) LoginUser(ctx context.Context, username string) (LoginUserRow, error) {
	row := q.db.QueryRow(ctx, loginUser, username)
	var i LoginUserRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const passwordHash = `-- name: PasswordHash :one
SELECT password_hash FROM users WHERE id=$1
`

func (q *Queries) PasswordHash(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, passwordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const sessionUser = `-- name: SessionUser :one
SELECT users.id,users.username FROM user_sessions
JOIN users ON users.id=user_sessions.user_id
WHERE user_sessions.token_hash=$1 AND user_sessions.expires_at>NOW()
`

type SessionUserRow struct {
	ID       int64
	Username string
}

func (q *Queries) SessionUser(ctx context.Context, tokenHash string) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, tokenHash)
	var i SessionUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash=$1,updated_at=NOW() WHERE id=$2
`

type UpdatePasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
