// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase.sql

package query

import (
	"context"
)

const clearPurchases = `-- name: ClearPurchases :exec
DELETE FROM next_month_purchases
WHERE user_id=$1 AND target_month=($2::text)::date
`

type ClearPurchasesParams struct {
	UserID  int64
	Column2 string
}

func (q *Queries) ClearPurchases(ctx context.Context, arg ClearPurchasesParams) error {
	_, err := q.db.Exec(ctx, clearPurchases, arg.UserID, arg.Column2)
	return err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO next_month_purchases (user_id,target_month,name,price,url)
VALUES ($1,($2::text)::date,$3,$4,$5)
RETURNING id,name,price,url
`

type CreatePurchaseParams struct {
	UserID  int64
	Column2 string
	Name    string
	Price   float64
	Url     *string
}

type CreatePurchaseRow struct {
	ID    int64
	Name  string
	Price float64
	Url   *string
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (CreatePurchaseRow, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.UserID,
		arg.Column2,
		arg.Name,
		arg.Price,
		arg.Url,
	)
	var i CreatePurchaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Url,
	)
	return i, err
}

const deletePurchase = `-- name: DeletePurchase :execrows
DELETE FROM next_month_purchases
WHERE id=$1 AND user_id=$2 AND target_month=($3::text)::date
`

type DeletePurchaseParams struct {
	ID      int64
	UserID  int64
	Column3 string
}

func (q *Queries) DeletePurchase(ctx context.Context, arg DeletePurchaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePurchase, arg.ID, arg.UserID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPurchases = `-- name: ListPurchases :many
SELECT id, name, price, url FROM next_month_purchases
WHERE user_id=$1 AND target_month=($2::text)::date
ORDER BY created_at DESC, id DESC
`

type ListPurchasesParams struct {
	UserID  int64
	Column2 string
}

type ListPurchasesRow struct {
	ID    int64
	Name  string
	Price float64
	Url   *string
}

func (q *Queries) ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]ListPurchasesRow, error) {
	rows, err := q.db.Query(ctx, listPurchases, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasesRow
	for rows.Next() {
		var i ListPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
